### ISSUE TITLE
 Okta JWT Verifier dependency vulnerability from Axios 

### ISSUE THREAD

**Issue by RomainGaillardLesEchos** [okta/okta-jwt-verifier-js#20]
### Describe the bug?

https://www.npmjs.com/package/@okta/jwt-verifier package uses 1.12.3 version of https://www.npmjs.com/package/jwks-rsa/v/1.12.3 which uses Axios < 0.21.2 which is impacted by (https://github.com/advisories/GHSA-cph5-m8f7-6c5x).

Please could you upgrade https://www.npmjs.com/package/@okta/jwt-verifier to next version (2.0.0).

### What is expected to happen?

Do not install  Axios < 0.21.2 in my project because this package is impacted by security vulnerabilities (https://github.com/advisories/GHSA-cph5-m8f7-6c5x.)

### What is the actual behavior?

install  Axios < 0.21.2 in my project and is making a security impact on them (https://github.com/advisories/GHSA-cph5-m8f7-6c5x.)

### Reproduction Steps?

npm install @okta/jwt-verifier

### SDK Versions

"@okta/jwt-verifier": "^2.3.0",

### Execution Environment

- Runtime: NodeJS v 16 
- Framework: NestJS v ^8.0.0
- MacOs Monterey v 12.5

**Comment by denysoblohin-okta** [comment]
Version 2.6.0 should install `axios ^0.27.2`
https://github.com/okta/okta-jwt-verifier-js/pull/19/files
