### ISSUE TITLE
Snyk Reported issue with @okta/jwt-verifier@3.0.0 > njwt@2.0.0 20:05:21   

### ISSUE THREAD

**Issue by RGanni49** [okta/okta-jwt-verifier-js#43]
### Describe the bug

<img width="592" alt="synk-okta-issue" src="https://github.com/okta/okta-jwt-verifier-js/assets/120459432/e7272aa4-0406-4777-aa2f-d7e1550addcc">

### Reproduction Steps?

We are trying to deploy in jenkins for nodejs application. and then synk has found a vulnerability with @okta/jwt-verifier@3.0.0 > njwt@2.0.0   
https://security.snyk.io/vuln/SNYK-JS-NJWT-6861582

### SDK Versions

@okta/jwt-verifier@3.0.0

**Comment by mohan26** [comment]
I am also getting the same issue

**Comment by jaredperreault-okta** [comment]
https://github.com/jwtk/njwt/pull/107

We are working on getting `njwt` patched

**Comment by jaredperreault-okta** [comment]
#46 `3.2.2` resolves this issue
